// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOl28K0CKgx3Mqg4JirRpSZ1d0DPlFGqo',
    appId: '1:377618963576:web:1e1be0f52849a161a0a18d',
    messagingSenderId: '377618963576',
    projectId: 'geoportal-a3727',
    authDomain: 'geoportal-a3727.firebaseapp.com',
    storageBucket: 'geoportal-a3727.firebasestorage.app',
    measurementId: 'G-JB4EGZ893B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhBi8CfHLvOFwD3ObmA8Veh_SMgEXzSKo',
    appId: '1:377618963576:android:e508ea1052aae2c7a0a18d',
    messagingSenderId: '377618963576',
    projectId: 'geoportal-a3727',
    storageBucket: 'geoportal-a3727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_Bvmd1kLaDFrXDI8XC2Zi2U00EzsRU8',
    appId: '1:377618963576:ios:fcce18742296a6ada0a18d',
    messagingSenderId: '377618963576',
    projectId: 'geoportal-a3727',
    storageBucket: 'geoportal-a3727.firebasestorage.app',
    iosBundleId: 'com.example.geoportalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_Bvmd1kLaDFrXDI8XC2Zi2U00EzsRU8',
    appId: '1:377618963576:ios:fcce18742296a6ada0a18d',
    messagingSenderId: '377618963576',
    projectId: 'geoportal-a3727',
    storageBucket: 'geoportal-a3727.firebasestorage.app',
    iosBundleId: 'com.example.geoportalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOl28K0CKgx3Mqg4JirRpSZ1d0DPlFGqo',
    appId: '1:377618963576:web:1e1be0f52849a161a0a18d',
    messagingSenderId: '377618963576',
    projectId: 'geoportal-a3727',
    authDomain: 'geoportal-a3727.firebaseapp.com',
    storageBucket: 'geoportal-a3727.firebasestorage.app',
    measurementId: 'G-JB4EGZ893B',
  );
}
